server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product_route
#          uri: http://localhost:8081
          uri: lb://service-product
          order: 1
          predicates:
            - Path=/product-serv/**
            - Method=Get
#            - Before=2000-11-28T00:00:00.000+08:00
          filters:
            - StripPrefix=1